#!/bin/bash
#SBATCH --job-name=olmo_finetune
#SBATCH --output=ResearchProject/logs/%x_%j.out
#SBATCH --time=00:10:00
#SBATCH --partition=scavenge
#SBATCH --cpus-per-task=16
#SBATCH --nodes=1
#SBATCH --gres=gpu:2
#SBATCH --nodelist=cn11,cn19,cn13,cn[3,6]

hostname

module load Anaconda3/2024.02-1

eval "$(conda shell.bash hook)"

conda activate captum_test

cd ResearchProject

torchrun --nproc_per_node=2 train.py --dry-run
