#!/bin/bash
#SBATCH --job-name=intgrads_small
#SBATCH --output=ResearchProject/logs/%x_%j.out
#SBATCH --time=12:00:00
#SBATCH --partition=scavenge
#SBATCH --cpus-per-task=32
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --nodelist=cn19,cn11,cn13,cn[3,6]
#SBATCH --mail-type=END

hostname

module load Anaconda3
module load CUDA

eval "$(conda shell.bash hook)"

conda activate counter 

cd ResearchProject/scripts

python3 intgrads.py
