#!/bin/bash
#SBATCH --job-name=intgrads
#SBATCH --output=ResearchProject/logs/%x_%j.out
#SBATCH --time=12:00:00
#SBATCH --partition=scavenge
#SBATCH --cpus-per-task=16
#SBATCH --nodes=1
#SBATCH --gres=gpu:2
#SBATCH --nodelist=cn19,cn11,cn13,cn[3,6]
#SBATCH --mail-type=END

hostname

module load Anaconda3

eval "$(conda shell.bash hook)"

conda activate counter 

cd ResearchProject

time python3 intgrads.py
